### ISSUE TITLE
What is the slice thickness of the shared data?

### ISSUE THREAD

**Issue by hnguyentt** [mr7495/COVID-CTset#1]
Hello,

Thank you very much for sharing the data. Could you share the thickness for each slice of your data?

I downloaded and observed them, the slices' thickness may be 2mm or more.

**Comment by mr7495** [comment]
Hi
Thank you for your interest in our work.
The slices thickness is equal to six.

**Comment by hnguyentt** [comment]
Thank you for your reply. There are three folders: SR2, SR3, and SR4. It seems that 6 is the slice thickness of SR2 & SR3. For SR4, it should be different, perhaps 2-3. Is that right?

**Comment by mr7495** [comment]
I appreciate you, for reminding us of this issue,  and sorry for answering late.
A new CSV file has been added at [this link](https://github.com/mr7495/COVID-CTset/blob/master/Patient_details.csv), that shows the thickness of each folder for each patient.

**Comment by hnguyentt** [comment]
@mr7495 thank you so much for the update.

**Comment by hnguyentt** [comment]
Hi @mr7495 and how about x_spacing and y_spacing of the data? Are all of them 1mm?

**Comment by mr7495** [comment]
Hello

Unfortunately, I am not aware of this detail. I share you one of the DICOM  files and I hope you can find the relative information from its metadata.
[IM00026.zip](https://github.com/mr7495/COVID-CTset/files/5418045/IM00026.zip)

**Comment by hnguyentt** [comment]
Thank you very much, @mr7495 
It is 0.734375 for both x and y axis. Could you please extract the tag `(0028, 0030) PixelSpacing` and `(0020,0037) ImageOrientationPatient` from dicom headers?

**Comment by mr7495** [comment]
Yes of course.
The details have been extracted and are available at the new attached CSV file.
I hope it would be helpful.
[Patient_details_extra.zip](https://github.com/mr7495/COVID-CTset/files/5424015/Patient_details_extra.zip)

**Comment by hnguyentt** [comment]
Thank you again! That's very kind of you. :")
