### ISSUE TITLE
Number of Classes

### ISSUE THREAD

**Issue by AlexTS1980** [mr7495/COVID-CTset#5]
hi there, great work. I want to combine your data with CNCB-NCOV for better generalization. I'm a bit confused about the classes: in the smaller data (12058 observation), the classes are COVID and Normal, but the about 450 patients are are referred to as unnormal (in the Normal) class. So what class are they?

**Comment by mr7495** [comment]
Hello
There are two classes in our dataset: covid and normal. If you use the data allocated to training and validation, there are 5 folds and in each fold the training and testing data are splitted. (CSV files are available). In fold 5 there are 450 covid images. Please explain your issue more clearly so I can help you. Thanks

**Comment by AlexTS1980** [comment]
It's in the csv file, a number of entries are called unnormal:
```
cdunnormal_patient151_SR_2_IM00008.tif | normal
```
Are they normal or Common Pneumonia?

**Comment by mr7495** [comment]
Sorry of answering late.
normal means normal without no infections to pneumonia.
