### ISSUE TITLE
There is a mismatch between COVID-CTset.zip and Train&Validation.zip.

### ISSUE THREAD

**Issue by WinterPan2017** [mr7495/COVID-CTset#6]
Examples are as follows {137covid_patient1_SR_2_IM00010.tif}, {cdunnormal_patient154_SR_2_IM00040.tif}, {157covid_patient130_SR_3_IM00020.tif}, {normalcd3_patient432_SR_2_IM00025.tif}. These are file names in Train&Validation.zip. I noticed that the first part of the file name should be the root folder name in COVID-CTset.zip, but root folders are  covid1, covid2, normal[1-10].

Is this a problem or my mistake?

**Comment by elnazsafi1990** [comment]
Hello 
Yes, the first characters show the root folder, but these are the original root folders. We changed their names in the full dataset in order to make it easier for the researchers to use.

**Comment by mr7495** [comment]
Hello
Yes, the first characters show the root folder, but these are the original root folders. We changed their names in the full dataset in order to make it easier for the researchers to use.

**Comment by WinterPan2017** [comment]
> Hello
> Yes, the first characters show the root folder, but these are the original root folders. We changed their names in the full dataset in order to make it easier for the researchers to use.

Ok, I get it now, thanks！
