### ISSUE TITLE
Tag information of DICOM

### ISSUE THREAD

**Issue by NovinceNO1** [mr7495/COVID-CTset#8]
I am trying to use this dataset to test our CT reconstruction algorithm, so I need to change between pixels values and CT values(HU) by the formula HU=pixels*slope+intercept.  Can you disclose the tag information of those CT images before they were transformed in to the format of 'tiff'?  Thanks!

**Comment by mr7495** [comment]
Dear researcher,

In this file [Patients_metadata.csv](https://github.com/mr7495/COVID-CTset/blob/master/Patients_metadata.csv), you can access all the metadata of each patient. Please note that each patient has three CT scans folders named SR_2, SR_3, SR_4. Some parameters may be different for each folder. The mentioned CSV file contains the necessary information of all the CT folders for every patient. If you search slope or intercept in the CSV file, you will find the needed values.

Good Luck!

**Comment by NovinceNO1** [comment]
@mr7495 Thanks for your timely reply. I tried to download the file  'Patients_metadata.csv', but each time I click the 'Download ' button,  it goes to a garbled site. I'm not sure whether it is my network error or there is something wrong with the file. It would be nice of you if you could check the file again.

**Comment by mr7495** [comment]
You are welcome!
This link will work:
https://github.com/mr7495/COVID-CTset/blob/master/Patients_metadata.zip
