### ISSUE TITLE
Property of projection geometry

### ISSUE THREAD

**Issue by NovinceNO1** [mr7495/COVID-CTset#9]
Hello, Mohammad, I downloaded the metadata of all patients, but I could not find information about the projection geometry, specifically, the number of angles and the number of detector pixels. Is it possibles that you provide the information about scanning geometry or share one file of projection data. I am trying to generate projection data from the CT images you shared, where the number of views and the number of detector pixels(bins) are particularly important. Appreciate if you could provide any information about those two parameters.

**Comment by mr7495** [comment]
Hello, Thank you for your interest in our work. All the metadata is shared at https://github.com/mr7495/COVID-CTset/blob/master/Patients_metadata.zip . If you can not find the parameter you are looking for, please investigate the DICOM file attached to this message and tell me the ID of the parameter you want. e.g. (0010, 1010) indicates the patient's age. I will extract the data, and I will share it with you.


[IM00028.zip](https://github.com/mr7495/COVID-CTset/files/6604019/IM00028.zip)

**Comment by NovinceNO1** [comment]
@mr7495, thanks for your kind reply.  I not clear how to identify the ID of the parameter. I read the 'IM0028.dcm' file into MATLAB with its built-in function dicominfo, and I got a struct, where a number of items were included, but they are not marked with numbers such as (0010, 1010). I carefully investigated  the struct I got, but there was no clue of detector pixels and angles scanned.  I am not sure if they are expressed with some kind of items that I do not understand, for example, there is an item called 'AcquisitionGroupLength' with value of 504.

**Comment by mr7495** [comment]
You are so welcome! please read the attached CSV file. In this file all the available metadata titles have been reported. If the parameter you want exists there, tell me its name so I give you its data for all the Ct-scan images.

[Patient_metadata_titles.zip](https://github.com/mr7495/COVID-CTset/files/6604642/Patient_metadata_titles.zip)
